import Link from "next/link"
import { notFound, redirect } from "next/navigation"
import { BorrowingReportAutoPrint, BorrowingReportPrintButton } from "@/app/borrowing-report/print-button"
import { getServerAuthSession } from "@/lib/auth/server"
import { getLabUsageReportData, getLabUsageReportFilters } from "@/lib/reports/lab-usage-report"
const fmt = (v: Date) => new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Jakarta" }).format(v)
export default async function LabUsageReport({ params, searchParams }: { params: Promise<{ type: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const [{ type }, raw] = await Promise.all([params, searchParams]); if (type !== "penggunaan-ruangan" && type !== "presensi") notFound()
  const session = await getServerAuthSession(); if (!session?.user?.id || (session.user.role !== "admin" && session.user.role !== "petugas_plp")) redirect("/dashboard/lab-usage")
  const report = await getLabUsageReportData({ role: session.user.role, userId: session.user.id, filters: getLabUsageReportFilters(raw) })
  const isUsage = type === "penggunaan-ruangan"; const usageById = new Map(report.usage.map((x) => [x.id, x])); const rows = isUsage ? report.usage : report.attendance
  return <main className="min-h-screen bg-muted/20 text-black print:bg-white"><BorrowingReportAutoPrint /><div className="mx-auto max-w-7xl p-4 print:max-w-none print:p-0"><div className="mb-4 flex justify-between print:hidden"><Link href="/dashboard/lab-usage">Kembali ke Penggunaan Lab</Link><BorrowingReportPrintButton /></div><section className="bg-white p-6 print:p-0"><h1 className="border-b-2 border-black pb-3 text-center text-lg font-bold uppercase">{isUsage ? "Rekap Penggunaan Ruangan" : "Rekap Presensi Penggunaan Ruangan"}</h1><table className="mt-4 w-full border-collapse text-[10px]"><thead><tr>{(isUsage ? ["No","Lab","Mata Kuliah/Kegiatan","Kelompok","Peserta","Mulai","Selesai"] : ["No","Lab","Mata Kuliah/Kegiatan","Kelompok","Mulai","Selesai","NIM","Nama"]).map(x => <th key={x} className="border border-black px-2 py-1 text-left">{x}</th>)}</tr></thead><tbody>{rows.length === 0 ? <tr><td colSpan={8} className="border border-black p-3 text-center">Tidak ada data.</td></tr> : isUsage ? report.usage.map((x,i)=><tr key={x.id}><td className="border border-black p-1">{i+1}</td><td className="border border-black p-1">{x.labName}</td><td className="border border-black p-1">{x.courseName}</td><td className="border border-black p-1">{x.groupName}</td><td className="border border-black p-1">{x.studentCount}</td><td className="border border-black p-1">{fmt(x.startedAt)}</td><td className="border border-black p-1">{fmt(x.endedAt)}</td></tr>) : report.attendance.map((x,i)=>{const u=usageById.get(x.usageLogId); return <tr key={`${x.usageLogId}-${i}`}><td className="border border-black p-1">{i+1}</td><td className="border border-black p-1">{u?.labName ?? "-"}</td><td className="border border-black p-1">{u?.courseName ?? "-"}</td><td className="border border-black p-1">{u?.groupName ?? "-"}</td><td className="border border-black p-1">{u ? fmt(u.startedAt) : "-"}</td><td className="border border-black p-1">{u ? fmt(u.endedAt) : "-"}</td><td className="border border-black p-1">{x.attendeeNim ?? "-"}</td><td className="border border-black p-1">{x.attendeeName}</td></tr>})}</tbody></table></section></div></main>
}
