-- Migrasi master bahan dari file migrasi-bahan-1.xlsx
-- Aturan:
-- 1. Duplikat bahan per kombinasi lab + nama + merk/tipe digabung
-- 2. Merk/Tipe digabung ke nama bahan bila tidak kosong
-- 3. category diisi kategori umum per lab
-- 4. unit diisi 'unit'
-- 5. min_stock_qty diisi 0
-- 6. code generated dengan prefix MIGB1

WITH item_seed (lab_name, item_code, item_name, category, unit, stock_qty, min_stock_qty, is_active) AS (
  VALUES
    ('Lab Entomologi', 'MIGB1-ENT-001-ABATE-62-5-GR', 'Abate - 62,5 GR', 'Entomologi', 'unit', 1, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-002-ALUMINIUM-FOIL', 'Aluminium Foil', 'Entomologi', 'unit', 9, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-003-ASPIRATOR', 'Aspirator', 'Entomologi', 'unit', 15, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-004-AWETAN-KERING-SERANGGA', 'Awetan Kering Serangga', 'Entomologi', 'unit', 2, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-005-AWETAN-KERING-VEKTOR', 'Awetan Kering Vektor', 'Entomologi', 'unit', 2, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-006-BAYGON-AEROSOL', 'Baygon Aerosol', 'Entomologi', 'unit', 12, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-007-BAYGON-ANTI-NYAMUK-BAKAR', 'Baygon Anti Nyamuk Bakar', 'Entomologi', 'unit', 4, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-008-BOTOL-UJI-CDC', 'Botol Uji CDC', 'Entomologi', 'unit', 2, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-009-COVER-GLASS', 'Cover Glass', 'Entomologi', 'unit', 18, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-010-DISSECTING-SET', 'Dissecting Set', 'Entomologi', 'unit', 2, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-011-FLY-SNIPERPLUS-100-GR', 'Fly Sniperplus - 100 GR', 'Entomologi', 'unit', 1, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-012-HIT-ANTI-KECOA-GEL', 'Hit Anti Kecoa Gel', 'Entomologi', 'unit', 2, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-013-HIT-ANTI-NYAMUK-KECOA-LIQU', 'Hit Anti Nyamuk Kecoa Liquid - 100 GR', 'Entomologi', 'unit', 1, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-014-HIT-ANTI-NYAMUK-KECOA-LIQU', 'Hit Anti Nyamuk Kecoa Liquid - 20 GR', 'Entomologi', 'unit', 3, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-015-JARUM-PINNING', 'Jarum Pinning', 'Entomologi', 'unit', 1, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-016-KACA-PEMBESAR', 'Kaca Pembesar', 'Entomologi', 'unit', 12, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-017-KACA-PREPARAT', 'Kaca Preparat', 'Entomologi', 'unit', 6, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-018-KAPAS', 'Kapas', 'Entomologi', 'unit', 11, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-019-KAPUR-ANTI-KECOA', 'Kapur Anti Kecoa', 'Entomologi', 'unit', 5, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-020-KAPUR-BARUS', 'Kapur Barus', 'Entomologi', 'unit', 2, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-021-KELAMBU', 'Kelambu', 'Entomologi', 'unit', 3, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-022-KERTAS-LABEL', 'Kertas Label', 'Entomologi', 'unit', 1, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-023-KERTAS-SARING', 'Kertas Saring', 'Entomologi', 'unit', 2, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-024-KLERAT', 'Klerat', 'Entomologi', 'unit', 8, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-025-LANCET-DEVICE', 'Lancet Device', 'Entomologi', 'unit', 2, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-026-LARVITRAP', 'Larvitrap', 'Entomologi', 'unit', 24, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-027-LEM-LALAT-360-ML', 'Lem Lalat - 360 ML', 'Entomologi', 'unit', 1, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-028-MASKER-RESPIRATOR', 'Masker Respirator', 'Entomologi', 'unit', 2, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-029-MINYAK-SEREH', 'Minyak Sereh', 'Entomologi', 'unit', 3, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-030-MUSCA-DOWN', 'Musca Down', 'Entomologi', 'unit', 14, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-031-PAPER-CUP', 'Paper Cup', 'Entomologi', 'unit', 20, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-032-PETROKUM-30-ML', 'Petrokum - 30 ML', 'Entomologi', 'unit', 1, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-033-PLASTIK-CUP', 'Plastik Cup', 'Entomologi', 'unit', 20, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-034-PLASTIK-KLIP', 'Plastik Klip', 'Entomologi', 'unit', 12, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-035-REPELLENT-AUTAN-1-KG', 'Repellent Autan - 1 KG', 'Entomologi', 'unit', 1, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-036-REPELLENT-SOFFEL-500-GR', 'Repellent Soffel - 500 GR', 'Entomologi', 'unit', 1, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-037-SEDIAAN-PREPARAT-KUTU', 'Sediaan Preparat Kutu', 'Entomologi', 'unit', 1, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-038-SEDIAAN-PREPARAT-LARVA', 'Sediaan Preparat Larva', 'Entomologi', 'unit', 2, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-039-SEDIAAN-PREPARAT-PINJAL', 'Sediaan Preparat Pinjal', 'Entomologi', 'unit', 1, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-040-SENTER', 'Senter', 'Entomologi', 'unit', 5, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-041-SISIR-KUTU', 'Sisir Kutu', 'Entomologi', 'unit', 3, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-042-SOLFAC-10WP', 'Solfac 10WP', 'Entomologi', 'unit', 1, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-043-STICKY-TRAP-1-KG', 'Sticky Trap - 1 KG', 'Entomologi', 'unit', 1, 0, true),
    ('Lab Entomologi', 'MIGB1-ENT-044-SUSCEPTIBILITY-TEST-KIT', 'Susceptibility Test Kit', 'Entomologi', 'unit', 1, 0, true),
    ('Lab Fisika dan Sanitasi Industri', 'MIGB1-FSI-001-BATERAI-AA-ALKALINE', 'Baterai AA - Alkaline', 'Fisika Sanitasi Industri', 'unit', 15, 0, true),
    ('Lab Fisika dan Sanitasi Industri', 'MIGB1-FSI-002-BATERAI-AAA-ALKALINE', 'Baterai AAA - Alkaline', 'Fisika Sanitasi Industri', 'unit', 15, 0, true),
    ('Lab Fisika dan Sanitasi Industri', 'MIGB1-FSI-003-KERTAS-FILTER-BULAT-WHATMA', 'Kertas filter bulat - Whatman 110 mm', 'Fisika Sanitasi Industri', 'unit', 40, 0, true),
    ('Lab Fisika dan Sanitasi Industri', 'MIGB1-FSI-004-KERTAS-FILTER-BULAT-WHATMA', 'Kertas filter bulat - Whatman 90 mm', 'Fisika Sanitasi Industri', 'unit', 40, 0, true),
    ('Lab Fisika dan Sanitasi Industri', 'MIGB1-FSI-005-KERTAS-FILTER-LEMBAR-WHATM', 'Kertas filter lembar - Whatman 105', 'Fisika Sanitasi Industri', 'unit', 290, 0, true),
    ('Lab Fisika dan Sanitasi Industri', 'MIGB1-FSI-006-KERTAS-FILTER-STERIL-WHATM', 'Kertas filter steril - Whatman Sterile Membrane', 'Fisika Sanitasi Industri', 'unit', 40, 0, true),
    ('Lab Fisika dan Sanitasi Industri', 'MIGB1-FSI-007-USB-DRIVE-KINGSTON', 'USB drive - Kingston', 'Fisika Sanitasi Industri', 'unit', 3, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-001-1-5-DIPHENYLCARBAZID-MERCK', '1,5 diphenylcarbazid - Merck / 25 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-002-ACETIC-ACID-MERCK-2-5LTR', 'Acetic Acid - Merck / 2.5ltr', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-003-ACETON-MERCK', 'Aceton - Merck', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-004-ACETONE-TEDIA-4-LTR', 'Acetone - Tedia / 4 ltr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-005-ACID-SAURAGE-MERCK-2-5-LTR', 'Acid Saurage - Merck / 2.5 ltr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-006-AMIDOSULFURIC-ACID-MERCK-2', 'Amidosulfuric Acid - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-007-AMMONIAC-KLOSUNG-MERCK-2-5', 'Ammoniac Klosung - Merck / 2.5 ltr', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-008-AMMONIUM-THIOCYANATE-MERCK', 'Ammonium Thiocyanate - Merck / 500 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-009-AMONIA-SOLUTION-MERCK-2-5', 'Amonia Solution - Merck / 2.5 ltr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-010-AMONIUM-IRON-II-SULFATE-ME', 'Amonium  Iron II sulfate - Merck / 1000 gr', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-011-AMONIUM-CHLORIDE-MERCK-100', 'Amonium Chloride - Merck / 1000 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-012-AMONIUM-THICYNAIT-MERCK-50', 'Amonium thicynait - Merck / 500 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-013-ASAM-OKSALAT-MERCK-500-GR', 'Asam Oksalat - Merck / 500 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-014-ASAM-SULFAMAT-MERCK-1000-G', 'asam sulfamat - Merck / 1000 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-015-ASAM-SULFAMAT-MERCK-250-GR', 'asam sulfamat - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-016-ASAM-SULFAT-PEKAT-MERCK-25', 'Asam Sulfat Pekat - Merck / 250', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-017-BARIUM-CHLORIDA-DIHIDRAT-M', 'Barium Chlorida dihidrat - Merck / 500 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-018-BARIUMCHLORIDE-BACL-MERCK', 'Bariumchloride / BaCl - Merck / 1000 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-019-BLEI-ACETAT-TRIHYDRAT-MERC', 'Blei (acetat-trihydrat) - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-020-BLEI-II-PB-NITRAT-MERCK-10', 'Blei(II) pB Nitrat - Merck / 100 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-021-BORSAURE-H3BO3-MERCK-1000', 'Borsaure h3bo3 - Merck / 1000 gr', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-022-BUTANOL-MERCK-1-LTR', 'Butanol - Merck / 1 ltr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-023-C13H14H4O-DIPHONYL-CARBAZI', 'C13H14H4O (Diphonyl carbazid) - Merck / 25 gr', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-024-C4HCKNAO6-4H2O-KALIUM-TART', 'C4HcKNaO6.4H2O(kalium tartat tetrahidrat) - Merck / 1000 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-025-CADMIUM-SULFATE-HYDRATE-ME', 'Cadmium Sulfate Hydrate - Merck / 100 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-026-CALSIUM-CARBONAT-MERCK-500', 'Calsium Carbonat - Merck / 500 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-027-CARBON-TETRACHLORIDE-ANALA', 'Carbon Tetrachloride - Analar / 2.5 ltr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-028-COPPER-II-CLORIDE-DIHYDRAT', 'Copper (II) Cloride Dihydrate - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-029-COPPER-SULFATE-PENTA-MERCK', 'Copper Sulfate Penta - Merck / 1000 gr', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-030-DI-NATRIUMHYDROGENPHOSPHAT', 'di - natriumhydrogenphosphat - Merck / 500 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-031-DIKALIUM-HIDROGEN-PHOSPAT', 'dikalium hidrogen phospat  trihidat - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-032-DI-KALIUM-HIDROGEN-PHOSPAT', 'di-kalium hidrogen phospat tihidrat - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-033-DITHIZONE-MERCK-5-GR', 'Dithizone - Merck / 5 gr', 'Kimia', 'unit', 3, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-034-EOSIN-RIEDEL-DEHEIN-25-GR', 'Eosin - Riedel-deHein / 25 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-035-EOSIN-2-LAB-BIONANALITIKA', 'Eosin 2% - Lab Bionanalitika Surabaya / 100 ml', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-036-EOSIN-2-MERCK-100-ML', 'Eosin 2% - Merck / 100 ml', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-037-EOSIN-G-MERCK-100-GR', 'Eosin G - Merck / 100 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-038-ESSIG-SAURE-RIEDEL-DEHEIN', 'Essig Saure - Riedel-deHein / 2.5 ltr', 'Kimia', 'unit', 3, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-039-ETHANOL-MERCK-2-5LTR', 'Ethanol - Merck / 2.5ltr', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-040-ETHYL-ETER-MALLIN-CHRODT-4', 'Ethyl Eter - Mallin chrodt / 4 ltr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-041-ETHYLE-DIMMONIUM-MERCK-250', 'Ethyle dimmonium - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-042-ETHYLENE-DYCLHORIDE-MERCK', 'Ethylene dyclhoride - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-043-FE-IRON-POWDER-MERCK-100-G', 'Fe / Iron Powder - Merck / 100 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-044-FERROIN-INDICATOR-SOLUTION', 'Ferroin Indicator Solution - Merck / 100 ml', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-045-FESO4-7H2O-EISEN-II-SULFAT', 'FeSo4 7H2O ( eisen (ii) sulfat heptahidrat) - Merck / 500 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-046-FORMALDEHYDE-SOLUTION-MALL', 'Formaldehyde Solution - Mallin chrodt / 4 ltr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-047-GARANTIESCHEIN-MERCK-25-GR', 'Garantieschein - Merck / 25 gr', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-048-GIEMSA-S-AZUR-EOSIN-MERCK', 'Giemsa''s Azur Eosin - Merck / 25 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-049-HEXANE-ANALAR-2-5-LTR', 'Hexane - Analar / 2.5 ltr', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-050-HYDROCLORIC-ACID-SIGMA-AL', 'Hydrocloric Acid - Sigma Al drich / 2.5 ltr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-051-IODINE-MERCK-25-GR', 'Iodine - Merck / 25 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-052-KALIUM-RIEDEL-DEHEIN-100-G', 'Kalium - Riedel-deHein / 100 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-053-KALIUM-CARBONATE-MERCK-250', 'Kalium carbonate - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-054-KALIUM-CARBONATE-MERCK-500', 'Kalium carbonate - Merck / 500 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-055-KALIUM-CHROMATE-MERCK-250', 'Kalium chromate - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-056-KALIUM-DICHROMAT-MERCK-500', 'Kalium Dichromat - Merck / 500 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-057-KALIUMIODAT-MERCK-1000-GR', 'Kaliumiodat - Merck / 1000 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-058-KALIUMIODAT-MERCK-500-GR', 'Kaliumiodat - Merck / 500 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-059-KALIUMIODAT-RIEDEL-DEHEIN', 'Kaliumiodat - Riedel-deHein / 100 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-060-KALSIUM-CHLORIDE-DIHIDRAT', 'kalsium chloride dihidrat - Merck / 500 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-061-KAPORIT-CA-OCL-2', 'Kaporit / Ca(OCl)2', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-062-KUPFER-II-MERCK-1000-GR', 'Kupfer II - Merck / 1000 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-063-LEAD-II-ACETAT-MERCK-250-G', 'Lead (II) Acetat - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-064-MANGAN-MERCK-250-GR', 'Mangan - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-065-MANGAN-II-SULFAT-MONOHYDRA', 'Mangan (II) sulfat monohydrat / MnSO4H20 - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-066-MANGANESE-II-MERCK-250-GR', 'Manganese II - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-067-MERCURY-II-CHLORIDE-NFPA-2', 'Mercury (II) Chloride - NFPA / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-068-MERCURY-II-CHLORIDE-HGCL2', 'Mercury (II) chloride (HgCl2) - Merck / 50 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-069-MERCURY-II-IODIDE-MERCK-50', 'Mercury (II) Iodide - Merck / 50 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-070-MERCURY-II-SULFAT-HGSO4-ME', 'Mercury (II) sulfat /HgSO4 - Merck / 50 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-071-MERCURY-II-IODIDE-MERCK-50', 'mercury (II)Iodide - Merck / 50 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-072-MERCURY-II-MERCK-250-GR', 'Mercury II - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-073-NAPTYL-ETHYLENE-DIAMINE-ME', 'Naptyl ethylene diamine - Merck / 25 gre', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-074-NATRIUM-AZID-MERCK-250-GR', 'Natrium azid - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-075-NATRIUM-BENZOAT-C6H5COONA', 'Natrium benzoat / C6H5CooNa - Merck / 1000 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-076-NATRIUM-CARBONATE-MERCK-10', 'Natrium Carbonate - Merck / 1000 gr', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-077-NATRIUM-CARBONATE-NA2CO3-1', 'natrium carbonate  Na2CO3+10 H20 - Merck / 1000 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-078-NATRIUM-CARBONATE-NA2CO3-M', 'natrium carbonate Na2CO3 - Merck / 1000 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-079-NATRIUM-HYDROGEN-MERCK-500', 'Natrium Hydrogen - Merck / 500 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-080-NATRIUM-NITRAT-MERCK-500-G', 'Natrium nitrat - Merck / 500 gr', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-081-NATRIUM-NITRIT-NANO2-MERCK', 'natrium nitrit / NaNO2 - Merck / 500 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-082-NATRIUM-THIOSULFAT-PENTAHY', 'Natrium Thiosulfat pentahydrat - Merck / 1000 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-083-NITRIC-ACID-MERCK-2-5-LTR', 'Nitric Acid - Merck / 2.5 ltr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-084-OXALIC-ACID-MERCK-250', 'Oxalic Acid - Merck / 250', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-085-PARAROSALNILIN-MERCK-25-GR', 'Pararosalnilin - Merck / 25 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-086-PENAMTHROLIN-MONOHYDRATE-M', 'Penamthrolin monohydrate - Merck / 5 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-087-PH-4-00-MERCK-1000-ML', 'pH 4.00 - Merck / 1000 ml', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-088-PH-7-00-MERCK-1000-ML', 'pH 7.00 - Merck / 1000 ml', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-089-PHENOL-MERCK-250-GR', 'Phenol - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-090-POTASSIUM-HYDROXIDE-MERCK', 'Potassium  Hydroxide - Merck / 1000 gr', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-091-POTASSIUM-CHLORIDE-MERCK-2', 'Potassium Chloride - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-092-POTASSIUM-CHROMATE-MERCK-2', 'potassium chromate - Merck / 250 gr', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-093-POTASSIUM-DICHROMATE-MERCK', 'Potassium dichromate - Merck / 500 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-094-POTASSIUM-HYDROXIDA-MERCK', 'Potassium hydroxida - Merck / 1000 gr', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-095-POTASSIUM-HYDROXIDE-KOH-ME', 'Potassium hydroxide / KOH - Merck / 1000 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-096-POTASSIUM-HYDROXIDE-KALIUM', 'Potassium Hydroxide/Kalium Hidroxide - Merck / 1000 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-097-POTASSIUM-PERMANGANAT-KMNO', 'Potassium permanganat / KMnO4 - SAP Chemical / 1000 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-098-POTASSIUM-SODIUM-TARTRATE', 'Potassium Sodium Tartrate - Merck / 1000 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-099-POTASSIUM-THIOCYNATE-MERCK', 'Potassium Thiocynate - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-100-QUECKSILBER-II-SULFAT-MERC', 'Quecksilber II Sulfat - Merck / 50 gr', 'Kimia', 'unit', 3, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-101-RESORCINOL-MERCK-100-GR', 'Resorcinol - Merck / 100 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-102-SALPETERSAURE-RIEDEL-DEHEI', 'Salpetersaure - Riedel-deHein / 2.5 ltr', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-103-SILVER-NITRATE-MERCK-25-GR', 'Silver nitrate - Merck / 25 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-104-SODIUM-AZIDE-MERCK-250-GR', 'Sodium Azide - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-105-SODIUM-CHLORID-NACL-MERCK', 'Sodium chlorid / NaCl - Merck / 1000 gr', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-106-SODIUM-CHLORIDE-MERCK-1000', 'Sodium Chloride - Merck / 1000 gr', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-107-SODIUM-CYANIDE-ANALA-R-500', 'Sodium cyanide - Anala R / 500 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-108-SODIUM-HIDROXIDE-MERCK-100', 'Sodium hidroxide - Merck / 1000 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-109-SODIUM-HYDROXIDE-MERCK-500', 'Sodium Hydroxide - Merck / 500 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-110-SODIUM-HYDROXIDE-MERCK-500', 'Sodium Hydroxide - Merck / 5000 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-111-SODIUM-HYPOCHLORITE-MERCK', 'Sodium Hypochlorite - Merck / 1000 ml', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-112-SODIUM-THIOCYNATE-HIMEDIA', 'Sodium Thiocynate - Himedia / 500 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-113-SODIUM-THIOSULFATE-MERCK-1', 'Sodium Thiosulfate - Merck / 1000 gr', 'Kimia', 'unit', 2, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-114-SODIUM-TRISULFAT-MERCK-100', 'Sodium trisulfat - Merck / 1000 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-115-STARCH-MERCK-250-GR', 'Starch - Merck / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-116-STARKE-RIEDEL-DEHEIN-250-G', 'Starke - Riedel-deHein / 250 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-117-SUKROSA-MERCK-1000-GR', 'sukrosa - Merck / 1000 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-118-SULFURIC-ACID-HONEYWEL-2-5', 'Sulfuric Acid - Honeywel / 2.5 ltr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-119-TAWAS', 'Tawas', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-120-TOLUENE-MALLIN-CHRODT-4-LT', 'Toluene - Mallin chrodt / 4 ltr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Kimia', 'MIGB1-KIM-121-ZINC-MERCK-500-GR', 'Zinc - Merck / 500 gr', 'Kimia', 'unit', 1, 0, true),
    ('Lab Penyehatan Makanan dan Minuman', 'MIGB1-PMM-001-DAGING-DAN-HATI-AYAM-FRESH', 'Daging dan Hati Ayam (Fresh) - Lokal', 'Penyehatan Makanan dan Minuman', 'unit', 4, 0, true),
    ('Lab Penyehatan Makanan dan Minuman', 'MIGB1-PMM-002-DAGING-SAPI-FRESH-LOKAL', 'Daging Sapi (Fresh) - Lokal', 'Penyehatan Makanan dan Minuman', 'unit', 2, 0, true),
    ('Lab Penyehatan Makanan dan Minuman', 'MIGB1-PMM-003-FROZEN-FOOD-BAKSO-SOSIS-NU', 'Frozen Food (Bakso, Sosis, Nugget ) - Curah', 'Penyehatan Makanan dan Minuman', 'unit', 8, 0, true),
    ('Lab Penyehatan Makanan dan Minuman', 'MIGB1-PMM-004-JAJANAN-PASAR-LOKAL', 'Jajanan Pasar - Lokal', 'Penyehatan Makanan dan Minuman', 'unit', 11, 0, true),
    ('Lab Penyehatan Makanan dan Minuman', 'MIGB1-PMM-005-KOREK-API-GAS-TOKAI', 'Korek Api Gas - Tokai', 'Penyehatan Makanan dan Minuman', 'unit', 50, 0, true),
    ('Lab Penyehatan Makanan dan Minuman', 'MIGB1-PMM-006-MAKANAN-KALENG-ABC', 'Makanan Kaleng - ABC', 'Penyehatan Makanan dan Minuman', 'unit', 22, 0, true),
    ('Lab Penyehatan Makanan dan Minuman', 'MIGB1-PMM-007-MIE-BASAH-LOKAL', 'Mie basah - Lokal', 'Penyehatan Makanan dan Minuman', 'unit', 10, 0, true),
    ('Lab Penyehatan Makanan dan Minuman', 'MIGB1-PMM-008-SAYURAN-WORTEL-BROKOLI-TOM', 'Sayuran (Wortel, Brokoli, Tomat, dll) - Lokal', 'Penyehatan Makanan dan Minuman', 'unit', 12, 0, true),
    ('Lab Penyehatan Makanan dan Minuman', 'MIGB1-PMM-009-SUSU-SAPI-CAIR-LOKAL', 'Susu Sapi Cair - Lokal', 'Penyehatan Makanan dan Minuman', 'unit', 20, 0, true),
    ('Lab Penyehatan Makanan dan Minuman', 'MIGB1-PMM-010-TELUR-BEBEK-LOKAL', 'Telur Bebek - Lokal', 'Penyehatan Makanan dan Minuman', 'unit', 150, 0, true),
    ('Lab Penyehatan Makanan dan Minuman', 'MIGB1-PMM-011-TEST-KIT-UJI-KANDUNGAN-BAK', 'Test Kit Uji Kandungan Bakteri pada Makanan - Teskit.id', 'Penyehatan Makanan dan Minuman', 'unit', 2, 0, true),
    ('Lab Penyehatan Makanan dan Minuman', 'MIGB1-PMM-012-TEST-KIT-UJI-KANDUNGAN-BOR', 'Test Kit Uji Kandungan Borax pada Makanan - Inagenpro', 'Penyehatan Makanan dan Minuman', 'unit', 1, 0, true),
    ('Lab Penyehatan Makanan dan Minuman', 'MIGB1-PMM-013-TEST-KIT-UJI-KANDUNGAN-FOR', 'Test Kit Uji Kandungan Formalin pada Makanan - Inagenpro', 'Penyehatan Makanan dan Minuman', 'unit', 1, 0, true),
    ('Lab Penyehatan Makanan dan Minuman', 'MIGB1-PMM-014-TEST-KIT-UJI-KANDUNGAN-MER', 'Test Kit Uji Kandungan Mercury (Hg) pada Makanan - Inagenpro', 'Penyehatan Makanan dan Minuman', 'unit', 1, 0, true),
    ('Lab Penyehatan Makanan dan Minuman', 'MIGB1-PMM-015-TEST-KIT-UJI-KANDUNGAN-RHO', 'Test Kit Uji Kandungan Rhodamin B pada Makanan - Inagenpro', 'Penyehatan Makanan dan Minuman', 'unit', 1, 0, true),
    ('Lab Penyehatan Makanan dan Minuman', 'MIGB1-PMM-016-TEST-KIT-UJI-KANDUNGAN-TIM', 'Test Kit Uji Kandungan Timbal (Pb) pada Makanan - Merck', 'Penyehatan Makanan dan Minuman', 'unit', 2, 0, true),
    ('Lab Penyehatan Makanan dan Minuman', 'MIGB1-PMM-017-TISSU-KERING-NICE', 'Tissu kering - Nice', 'Penyehatan Makanan dan Minuman', 'unit', 6, 0, true)
)
INSERT INTO consumable_items (
  lab_id,
  code,
  name,
  category,
  unit,
  stock_qty,
  min_stock_qty,
  is_active
)
SELECT
  l.id,
  s.item_code,
  s.item_name,
  s.category,
  s.unit,
  s.stock_qty,
  s.min_stock_qty,
  s.is_active
FROM item_seed s
INNER JOIN labs l ON l.name = s.lab_name
ON CONFLICT (code) DO NOTHING;
